### ISSUE TITLE
Ainneve fails to start under Evennia Dev 0.8

### ISSUE THREAD

**Issue by aliceafterall** [evennia/ainneve#111]
## Problem
When attempting to start Ainneve under Evennia's develop branch (0.8), we get a traceback:
```
Traceback (most recent call last):
  File "/home/nmatlaga/.virtualenvs/evennia/bin/evennia", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/nmatlaga/Projects/evennia/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/server/evennia_launcher.py", line 2018, in main
    init_game_directory(CURRENT_DIR, check_db=check_db)
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/server/evennia_launcher.py", line 1608, in init_game_directory
    django.setup()
  File "/home/nmatlaga/.virtualenvs/evennia/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nmatlaga/.virtualenvs/evennia/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/nmatlaga/.virtualenvs/evennia/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/typeclasses/models.py", line 38, in <module>
    from evennia.typeclasses.attributes import Attribute, AttributeHandler, NAttributeHandler
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/typeclasses/attributes.py", line 20, in <module>
    from evennia.locks.lockhandler import LockHandler
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/locks/lockhandler.py", line 617, in <module>
    _LOCK_HANDLER = LockHandler(_ObjDummy())
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/locks/lockhandler.py", line 180, in __init__
    _cache_lockfuncs()
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/locks/lockhandler.py", line 145, in _cache_lockfuncs
    _LOCKFUNCS.update(utils.callables_from_module(modulepath))
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/utils/utils.py", line 1305, in callables_from_module
    mod = mod_import(module)
  File "/home/nmatlaga/Projects/evennia/evennia/evennia/utils/utils.py", line 1233, in mod_import
    mod = __import__(module, fromlist=["None"])
  File "/home/nmatlaga/Projects/evennia/ainneve/server/conf/lockfuncs.py", line 23, in <module>
    from typeclasses.combat_handler import COMBAT_DISTANCES
  File "/home/nmatlaga/Projects/evennia/ainneve/typeclasses/combat_handler.py", line 5, in <module>
    from .scripts import Script
  File "/home/nmatlaga/Projects/evennia/ainneve/typeclasses/scripts.py", line 18, in <module>
    class Script(DefaultScript):
TypeError: Error when calling the metaclass bases
    cannot create 'NoneType' instances
```

Not a lot of fun, and if you remove the lockfunc in question everything works again.

**Comment by TehomCD** [comment]
That can happen when evennia's init method hasn't been called, so `DefaultScript` is still None, resulting in `cannot create 'NoneType' instances`.

**Comment by aliceafterall** [comment]
It is strange though, as it doesn't happen currently under 0.7, but does under 8. Removing the lockfunc does fix it, so I assume you're right.

**Comment by Griatch** [comment]
Hm, the `_LOCK_HANDLER = LockHandler(_ObjDummy())` is new in 0.8, it's there so that you can do stand-alone lock checks against lock strings without needing to use the lockhandler of an object first. Maybe that needs to be under a delayed execution to avoid this issue.

**Comment by Griatch** [comment]
@chainsol In https://github.com/evennia/evennia/commit/9d98a59be3b8e42e4833b8c2c251740931101ad1 I change the order of import for the lockhandler dummy upstream. Could you check if that helps with this issue?

**Comment by aliceafterall** [comment]
@Griatch: This fixes it, excellent! Thanks!
