### ISSUE TITLE
evennia start throws stacktrace in ainneve

### ISSUE THREAD

**Issue by feoh** [evennia/ainneve#43]
```
74 static files copied to '/Users/cpatti/src/personal/mymud/ainneve/web/static'.

Starting Evennia Server (output to stdout).

Starting Evennia Portal in Daemon mode (output to portal logfile).
cpatti@MBP15-04484 11:59:38 ~/src/personal/mymud/ainneve |master ✓| →   Server started for the first time. Setting defaults.
 Creating objects (Player #1 and Limbo room) ...
--------------------------------------------------
 Ainneve Portal (0.5.0 (rev 7f11256)) started.
  amp (to Server): 5000
  telnet: 4000
  webproxy:8000 (<-> 5001)
   + client (None:8001)
--------------------------------------------------
Unhandled Error
Traceback (most recent call last):
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/twisted/application/app.py", line 413, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/twisted/application/app.py", line 424, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/twisted/persisted/sob.py", line 207, in loadValueFromFile
    eval(codeObj, d, d)
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/server/server.py", line 464, in <module>
    EVENNIA = Evennia(application)
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/server/server.py", line 157, in __init__
    self.run_initial_setup()
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/server/server.py", line 249, in run_initial_setup
    initial_setup.handle_setup(0)
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/server/initial_setup.py", line 211, in handle_setup
    setup_func()
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/server/initial_setup.py", line 98, in create_objects
    nohome=True)
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/utils/create.py", line 123, in create_object
    new_object.save()
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/utils/idmapper/models.py", line 383, in save
    super(SharedMemoryModel, self).save(*args, **kwargs)
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/cpatti/src/personal/mymud/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/typeclasses/models.py", line 76, in post_save
    instance.at_first_save()
  File "/Users/cpatti/src/personal/mymud/evennia/evennia/objects/objects.py", line 824, in at_first_save
    self.at_object_creation()
  File "/Users/cpatti/src/personal/mymud/ainneve/typeclasses/characters.py", line 159, in at_object_creation
    self.base_stat(stat.name.lower(), rulebook.roll_stat())
exceptions.AttributeError: 'str' object has no attribute 'name'


Failed to load application: 'str' object has no attribute 'name'
```

**Comment by whitenoiseoss** [comment]
This is due to the **str** method on Trait. I can fix this.

**Comment by feoh** [comment]
Cool beans!

We should get some continuous integration going here :)
