### ISSUE TITLE
Chargen error message

### ISSUE THREAD

**Issue by abbacode** [evennia/ainneve#66]
I am using Windows 8.1 with Python 2.7.1 and I've noticed problems with the chargen command.

Using a fresh install, I login as the super user and attempt to create a new character:

<snip>
@charcreate temp

Welcome to Ainneve, the example game for Evennia.

To begin, select an Archetype. There are three base
archetypes to choose from, plus three dual archetypes which
combine the strengths and weaknesses of two archetypes into one.

Select an Archetype by number below to view its details, or help
at any time for more info.

  1: Arcanist        5: Warrior-Arcanist  
  2: Scout           6: Arcanist-Scout  
  3: Warrior  
  4: Warrior-Scout                               

I select any number and it generates the following traceback:

`Menu object not found as abba(player 1).ndb._menutree!
An untrapped error occurred. Please file a bug report detailing the
steps to reproduce. Server log time stamp is '2016-03-22 19:47:38+1100'.
A command handler bug occurred. Please file a bug report with the
Evennia project. Include the relvant traceback from the server log at
time stamp '2016-03-22 19:47:38+1100'.`

The traceback is:

2016-03-22 20:00:48+1100 [AMPProtocol,0,127.0.0.1] [..] Logged in: abba(player 1) ('127.0.0.1', 55528) (1 session(s) total)
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::]   File "d:\github\evennia\evennia\commands\cmdhandler.py", line 435, in _run_command
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::]     ret = yield cmd.func()
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::]   File "d:\github\evennia\evennia\utils\evmenu.py", line 202, in func
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::]     raise EvMenuError(err)
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::] EvMenuError: Menu object not found as abba(player 1).ndb._menutree!
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::]   File "d:\github\evennia\evennia\commands\cmdhandler.py", line 569, in cmdhandler
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::]     ret = yield _run_command(syscmd, syscmd.key, sysarg)
2016-03-22 20:00:51+1100 [AMPProtocol,0,127.0.0.1] [::] ErrorReported

**Comment by feend78** [comment]
Hi @abbacode,

I'm not able to reproduce this error locally. Could you confirm that you have updated your Evennia codebase to the current master?

**Comment by abbacode** [comment]
@feend78, sorry, silly mistake on my behalf.

I've been updating the Ainneve codebase, but not the Evennia one.  That was indeed the source of the problem and it has now been resolved.

Please feel free to close this issue.
